src/main/java/de/oglimmer/scg/web/action/SelectActionBean.java
package de.oglimmer.scg.web.action;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Map;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.RedirectResolution;
import net.sourceforge.stripes.action.Resolution;
import de.oglimmer.scg.core.AssociatedCard;
import de.oglimmer.scg.core.Card;
import de.oglimmer.scg.core.CardStack;
import de.oglimmer.scg.core.Game;
import de.oglimmer.scg.core.Messages;
import de.oglimmer.scg.core.Player;
import de.oglimmer.scg.printer.PrinterGamePlan;
import de.oglimmer.scg.printer.PrinterPlayerPlan;
import de.oglimmer.scg.printer.PrinterPlayerPlanHtml;
import de.oglimmer.scg.web.GameEndTextBuilder;
import de.oglimmer.scg.web.GameManager;

@Data
@EqualsAndHashCode(callSuper = false)
public class SelectActionBean extends BaseAction {

	private String gid;
	private String pid;

	private Collection<PlayerWeb> players;
	private Collection<CardWeb> callingPlayersCards;

	private Messages callingPlayersMessages;

	private Map<String, Integer> usedCards;
	private int undisclosedCards;

	private Game game;

	public String getGameWinner() {
		GameEndTextBuilder getb = new GameEndTextBuilder(game);
		getb.buildGameEndText();
		return getb.toString().replace(PrinterGamePlan.CR, "<br/>");
	}

	public Card getCard(int no) {
		return Card.get(no);
	}

	public int getCardCount(int no) {
		return CardStack.NUMBER_OF_CARDS[no - 1];
	}

	@DefaultHandler
	public Resolution show() {
		game = GameManager.INSTANCE.getGame(gid);
		if (game != null) {
			return showGame();
		} else {
			return getNoGameFoundResolution();
		}
	}

	private Resolution showGame() {
		Player callingPlayer = game.getPlayer(pid);
		return showPlayer(callingPlayer);
	}

	private Resolution showPlayer(Player callingPlayer) {
		buildResponse(callingPlayer);
		if (isPlayersTurn(callingPlayer)) {
			return getDisplayTurnResolution();
		} else {
			return getNoTurnResolution();
		}
	}

	private boolean isPlayersTurn(Player callingPlayer) {
		return callingPlayer.isCurrentPlayer();
	}

	private Resolution getNoTurnResolution() {
		return new ForwardResolution("/WEB-INF/jsp/noTurn.jsp");
	}

	private Resolution getDisplayTurnResolution() {
		return new ForwardResolution("/WEB-INF/jsp/select.jsp");
	}

	private Resolution getNoGameFoundResolution() {
		return new RedirectResolution(LandingActionBean.class);
	}

	private void buildResponse(Player callingPlayer) {
		Game game = callingPlayer.getGame();
		buildMessages(callingPlayer);
		buildCardStacks(game);
		buildCallingPlayersCards(callingPlayer);
		buildPlayerOverview(game);
	}

	private void buildPlayerOverview(Game game) {
		players = new ArrayList<>();
		for (Player player : game.getPlayers()) {
			players.add(new PlayerWeb(player));
		}
	}

	private void buildCallingPlayersCards(Player callingPlayer) {
		callingPlayersCards = new ArrayList<>();
		for (AssociatedCard card : callingPlayer.getCardHand().getAssociatedCards()) {
			callingPlayersCards.add(new CardWeb(card));
		}
	}

	private void buildCardStacks(Game game) {
		undisclosedCards = game.getStackHidden().getCards().size();
		PrinterGamePlan pgp = new PrinterGamePlan(game);
		usedCards = pgp.aggregateDataUsedCards();
	}

	private void buildMessages(Player callingPlayer) {
		callingPlayersMessages = callingPlayer.getMessages();
	}

	@AllArgsConstructor
	public class CardWeb {

		private AssociatedCard card;

		public int getNo() {
			return card.getCard().getNo();
		}

		public String getForm() {
			PrinterPlayerPlan ppp = new PrinterPlayerPlanHtml(card.getCard().getOwner());
			ppp.addCard(card);
			return ppp.toString();
		}
	}

	@AllArgsConstructor
	public class PlayerWeb {

		private Player player;

		public String getDisplayName() {
			Game game = GameManager.INSTANCE.getGame(gid);
			Player callingPlayer = game.getPlayer(pid);
			if (player == callingPlayer) {
				return "You are";
			}
			return player.getDisplayName() + " is";
		}

		public String getStatus() {
			PrinterPlayerPlan ppp = new PrinterPlayerPlan(player);
			ppp.addStatus();
			return ppp.toString();
		}

		public String getTurn() {
			return player.isCurrentPlayer() ? "(Turn owner)" : "";
		}

	}
}

src/main/webapp/WEB-INF/jsp/createGame.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"
	session="false"%>
<%@include file="/WEB-INF/jsp/common/include_taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/main_layout.jsp">
	<s:layout-component name="center">

		<s:form beanclass="de.oglimmer.scg.web.action.CreateGameActionBean"
			focus="">
			<div>
				<label for="email1">Email 1</label>
				<s:text name="email1" />
			</div>
			<div>
				<label for="email2">Email 2</label>
				<s:text name="email2" />
			</div>
			<div>
				<label for="email3">Email 3</label>
				<s:text name="email3" />
			</div>
			<div>
				<label for="email4">Email 4</label>
				<s:text name="email4" />
			</div>
			<s:submit name="create" value="create" />
		</s:form>

	</s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/jsp/createGameDone.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"
	session="false"%>
<%@include file="/WEB-INF/jsp/common/include_taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/main_layout.jsp">
	<s:layout-component name="center">

		Game created. Email sent.

	</s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/jsp/dead.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"
	session="false"%>
<%@include file="/WEB-INF/jsp/common/include_taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/main_layout.jsp">
	<s:layout-component name="center">

		<div>You died.</div>
		
		<div>
			${actionBean.response }
		</div>
	
		<div style="margin-bottom:20px">
		
			<s:link beanclass="de.oglimmer.scg.web.action.SelectActionBean">
				<s:param name="gid">${actionBean.gid}</s:param>
				<s:param name="pid">${actionBean.pid}</s:param>
				To overview page.
			</s:link>
		
		</div>
	
	</s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/jsp/debug.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"
	session="false"%>
<%@include file="/WEB-INF/jsp/common/include_taglibs.jsp"%>
<%
	pageContext.setAttribute("newLineChar", "\n");
%>

<s:layout-render name="/WEB-INF/jsp/common/main_layout.jsp">
	<s:layout-component name="center">

		<c:forEach var="game" items="${actionBean.gameManager.allGames }">
			${fn:replace(game.debugPrint(), newLineChar, '<br/>')}
			<s:link beanclass="de.oglimmer.scg.web.action.DebugActionBean"
				event="delete">
				<s:param name="gameId">${game.id }</s:param>
				Del
			</s:link>
			<s:link beanclass="de.oglimmer.scg.web.action.DebugActionBean"
				event="resendEmail">
				<s:param name="gameId">${game.id }</s:param>
				Resend
			</s:link>
			<hr />
		</c:forEach>

	</s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/jsp/do.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"
	session="false"%>
<%@include file="/WEB-INF/jsp/common/include_taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/main_layout.jsp">
	<s:layout-component name="center">
	
	<div style="margin-bottom:20px">
		Turn accepted.
	</div>
	
	<div style="margin-bottom:20px">
		${actionBean.response }
	</div>

	<div style="margin-bottom:20px">
		Next email sent.
	</div>
	
	<div style="margin-bottom:20px">
	
		<s:link beanclass="de.oglimmer.scg.web.action.SelectActionBean">
			<s:param name="gid">${actionBean.gid}</s:param>
			<s:param name="pid">${actionBean.pid}</s:param>
			To overview page.
		</s:link>
	
	</div>
	
	
	</s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/jsp/gameover.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"
	session="false"%>
<%@include file="/WEB-INF/jsp/common/include_taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/main_layout.jsp">
	<s:layout-component name="center">

		<div style="margin-bottom:20px">The has ended. See your inbox for the result.</div>
		
		<div style="margin-bottom:20px">
		
			<s:link beanclass="de.oglimmer.scg.web.action.SelectActionBean">
				<s:param name="gid">${actionBean.gid}</s:param>
				<s:param name="pid">${actionBean.pid}</s:param>
				To overview page.
			</s:link>
		
		</div>

	</s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/jsp/landing.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"
	session="false"%>
<%@include file="/WEB-INF/jsp/common/include_taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/main_layout.jsp">
	<s:layout-component name="center">

		<h1>Rules</h1>
		
			<ul>
				<li>You have 1 card in your hand</li>
				<li>At your turn you draw one new card</li>
				<li>You must always play one out of two cards</li>
				<li>When you play a card, its text takes effect</li>
				<li>In the beginning the undisclosed card stack has 10 cards</li>
				<li>The game ends when all 10 cards are drawn or only one player survived</li>
				<li>If more than 1 player survived the player with the highest card in his/her hand wins</li>
			</ul>
			
		<h1>How to play</h1>
		
		<p>
		There are 3 ways to play the game:
		</p>
		
		<ul>
			<li>Play within the Email-Client: if your email client supports html-forms you can just press one of the two "play" buttons below the cards. Unfortunately some email clients think html-forms are evil and don't support them.</li>
			<li>Play in the browser: click the link "Play via Browser" at the bottom of the email.</li>
			<li>Play by reply: press reply and use the follow answer (keep the original email in your reply): x-y-z. x = card 1 or 2, y = (optional) target player number, z = (optional) target card no</li>
		</ul>

		<h1>Cards</h1>
		
		<%@include file="/WEB-INF/jsp/common/card_overview.jsp"%>
		
		<div>
			&nbsp;
		</div>

	</s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/jsp/noTurn.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"
	session="false"%>
<%@include file="/WEB-INF/jsp/common/include_taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/main_layout.jsp">
	<s:layout-component name="center">
	
		<c:if test="${actionBean.game.turn.gameEnded}">
			<h2>Game Ended!</h2>
			${actionBean.gameWinner }
		</c:if>

		<h3>
			Players:
		</h3>
		<c:forEach var="player" items="${actionBean.players }">
			<li>${player.displayName } ${player.status } ${player.turn }</li>
		</c:forEach>
	
		<h3>
			Your cards:
		</h3>
		<table>
			<tr>
				<c:forEach var="card" items="${actionBean.callingPlayersCards }">
					<td><img src="images/card${card.no }.png"/></td>
				</c:forEach>
			</tr>
		</table>
	
		<h3>
			Stacks:
		</h3> 
		Undisclosed cards: ${actionBean.undisclosedCards }<br/>
		Used cards: 
		<c:forEach var="usedCard" items="${actionBean.usedCards }" varStatus="loopStatus">
			${usedCard.key }(${usedCard.value }x)
			<c:if test="${!loopStatus.last}">, </c:if>
		</c:forEach>
	
		<h3>
			Last actions:
		</h3>	
		<ol>
			${actionBean.callingPlayersMessages.allHtml }
		</ol> 
		
		
		<h3>Cards Help</h3>
			
		<%@include file="/WEB-INF/jsp/common/card_overview.jsp"%>
		

	</s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/jsp/select.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"
	session="false"%>
<%@include file="/WEB-INF/jsp/common/include_taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/main_layout.jsp">
	<s:layout-component name="center">
	
		<h3>
			Players:
		</h3>
		<c:forEach var="player" items="${actionBean.players }">
			<li>${player.displayName } ${player.status }</li>
		</c:forEach>
	
		<h3>
			Your cards:
		</h3>
		<table>
			<tr>
				<c:forEach var="card" items="${actionBean.callingPlayersCards }">
					<td>${card.form }</td>
				</c:forEach>
			</tr>
		</table>
	
		<h3>
			Stacks:
		</h3> 
		Undisclosed cards: ${actionBean.undisclosedCards }<br/>
		Used cards: 
		<c:forEach var="usedCard" items="${actionBean.usedCards }" varStatus="loopStatus">
			${usedCard.key }(${usedCard.value }x)
			<c:if test="${!loopStatus.last}">, </c:if>
		</c:forEach>
	
		<h3>
			Last actions:
		</h3>	
		<ol>
			${actionBean.callingPlayersMessages.allHtml }
		</ol> 
		
		
		<h3>Cards Help</h3>
			
		<%@include file="/WEB-INF/jsp/common/card_overview.jsp"%>

	
	</s:layout-component>
</s:layout-render>